source 'https://github.com/Nelozx/cocoapods-specs.git'

use_frameworks!

platform :ios, '10.0'

install! 'cocoapods', :warn_for_unused_master_specs_repo => false

target 'Popups_Example' do
  pod 'Popups', :path => '../'
#  pod 'Popups'
  pod 'SnapKit'
  
  target 'Tests' do
    
  end
end
